FROM alpine:3.4

RUN apk update \
  && apk --update add nodejs

RUN mkdir -p /react
WORKDIR /react

# キャッシュ効率を上げるためにまずpackage.jsonだけcopyしてnpm installする
COPY ./package.json /react/package.json
COPY ./npm-shrinkwrap.json /react/npm-shrinkwrap.json
RUN npm install

COPY ./.babelrc /react/.babelrc

COPY ./gulpfile.babel.js /react/gulpfile.babel.js

CMD ["npm", "run", "dev"]
